#!/system/bin/sh

#sync
#mount -o remount,rw /system

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#
# General Queue Tweaks
#
for i in /sys/block/*/queue; do
  echo 512 > $i/nr_requests;
  echo 256 > $i/read_ahead_kb;
  echo 2 > $i/rq_affinity;
  echo 0 > $i/nomerges;
  echo 0 > $i/add_random;
  echo 0 > $i/rotational;
done;

for i in `find /sys/devices/platform -name iostats`; do echo "0" > $i; done

#
# File System Tweaks & Cleanup
#
#busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,data=writeback /system
#for m in "/data" "/cache"; do
#  busybox mount -o remount,commit=19,barrier=0,nomblk_io_submit,noauto_da_alloc,errors=continue,noatime,nodiratime,nosuid,nodev,data=writeback $m
#done

#sync
#mount -o remount,ro /system
