#!/system/bin/sh
# - sysctl -p
#

#Set CPU min frequencies
echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
echo 384000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq;
echo 384000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq;
echo 384000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq;
#Set CPU max frequencies
echo 1728000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
echo 1728000 > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq;
echo 1728000 > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq;
echo 1728000 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq;

#Set GPU Frequency
echo 409500000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/max_gpuclk;
echo 409500000 > /sys/devices/platform/kgsl-3d0.0/kgsl/kgsl-3d0/gpuclk;
